name: Build SunamoReflection

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoReflection
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoReflection/SunamoReflection.csproj

    - name: Build
      run: dotnet build SunamoReflection/SunamoReflection.csproj --configuration Release --no-restore

  test:
    name: Test SunamoReflection.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoReflection.Tests/SunamoReflection.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoReflection.Tests/SunamoReflection.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoReflection.Tests/SunamoReflection.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
